version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: lumen-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/var/www/public
    depends_on:
      - app
    networks:
      - lumen-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumen-app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:TESTKEYFORLUMEN=
    networks:
      - lumen-network

  redis:
    image: redis:6-alpine
    container_name: lumen-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - lumen-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: lumen-worker
    command: php artisan process:csv
    volumes:
      - ./:/var/www
    depends_on:
      - app
      - redis
    networks:
      - lumen-network

networks:
  lumen-network:
    driver: bridge
